# Generated by Django 5.2.9 on 2025-12-09 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=200)),
                ('media_type', models.CharField(choices=[('book', 'Book'), ('audiobook', 'Audiobook'), ('dvd', 'DVD'), ('cd', 'Music CD'), ('magazine', 'Magazine')], max_length=20)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True)),
                ('barcode', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('checked_out', 'Checked Out'), ('on_hold', 'On Hold'), ('in_transit', 'In Transit'), ('lost', 'Lost')], default='available', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('card_number', models.CharField(max_length=20, unique=True)),
                ('pin_hash', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_out_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('renewals', models.IntegerField(default=0)),
                ('media_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.mediaitem')),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.patron')),
            ],
        ),
        migrations.CreateModel(
            name='MediaRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('media_type', models.CharField(choices=[('book', 'Book'), ('audiobook', 'Audiobook'), ('dvd', 'DVD/Blu-ray'), ('cd', 'Music CD'), ('magazine', 'Magazine/Journal'), ('other', 'Other')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('notify_when_available', models.BooleanField(default=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.librarian')),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.patron')),
            ],
        ),
        migrations.CreateModel(
            name='Hold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready for Pickup'), ('in_transit', 'In Transit'), ('picked_up', 'Picked Up'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('queue_position', models.IntegerField(default=1)),
                ('pickup_by', models.DateTimeField(blank=True, null=True)),
                ('pickup_location', models.CharField(default='Main Branch', max_length=100)),
                ('media_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.mediaitem')),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.patron')),
            ],
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('reason', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('checkout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.checkout')),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.patron')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('checkout', 'Checkout'), ('checkin', 'Check In'), ('hold_placed', 'Hold Placed'), ('hold_cancelled', 'Hold Cancelled'), ('request_submitted', 'Request Submitted'), ('request_approved', 'Request Approved'), ('patron_created', 'Patron Created'), ('renewal', 'Renewal')], max_length=30)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('librarian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.librarian')),
                ('media_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.mediaitem')),
                ('patron', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.patron')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
